name: testelw
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1


vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_fonts: ^1.1.1
  equatable: ^1.2.5
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter


dev_dependencies:
  effective_dart: ^1.3.0
  mockito: ^4.1.3
  modular_codegen: ^2.0.1
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - assets/img/

  fonts:
    - family: FeEngschrift 
      fonts:
        - asset: assets/fonts/fe_engschrift.ttf

